#!/bin/bash
LISTENING_HOST=127.0.0.1
LISTENING_TOPORT=80
LISTENING_ONPORT=8899

SSHD_HOST=host.ru
SSHD_USER=root
SSHD_PORT=22

COMMAND="ssh -c aes256-ctr -f -N -R $LISTENING_ONPORT:$LISTENING_HOST:$LISTENING_TOPORT $SSHD_USER@$SSHD_HOST"

if nc -z $SSHD_HOST $LISTENING_ONPORT
then
    echo "port $SSHD_HOST:$LISTENING_ONPORT up!"
else
    echo "Port $SSHD_HOST:$LISTENING_ONPORT is down"
	killall "ssh"
	$COMMAND
fi
